import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "NFt Core App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}   antialiased bg-[#080B2A]`}
      >
        {children}
      </body>
    </html>
  );
}
